### ISSUE TITLE
move to gulp

### ISSUE THREAD

**Issue by andyperlitch** [DataTorrent/malhar-angular-dashboard#113]
gulp is just... better.

**Comment by andyperlitch** [comment]
fixed in the release-2.0.0 branch

**Comment by awashbrook** [comment]
hi @andyperlitch, we are also trying to adopt gulp and protractor for e2e tests.

```
[andywash:~/web/dashboards/malhar-angular-dashboard]$ gulp protractor
[09:01:22] Using gulpfile ~/web/dashboards/malhar-angular-dashboard/gulpfile.js
[09:01:22] Starting 'styles'...
[09:01:22] Starting 'webdriver-update'...
[09:01:22] gulp-inject 2 files into index.less.
selenium standalone is up to date.
chromedriver is up to date.
[09:01:23] Finished 'webdriver-update' after 241 ms
[09:01:23] Finished 'styles' after 1.45 s
[09:01:23] Starting 'inject'...
[09:01:23] gulp-inject 1 files into index.html.
[09:01:23] gulp-inject 20 files into index.html.
[09:01:23] Finished 'inject' after 312 ms
[09:01:23] Starting 'serve:e2e'...
[09:01:24] Finished 'serve:e2e' after 50 ms
[09:01:24] Starting 'protractor:src'...
[BS] Local URL: http://localhost:3000/
[BS] External URL: http://192.168.0.10:3000/
[BS] Serving files from: .tmp/serve
[BS] Serving files from: src

module.js:340
    throw err;
          ^
Error: Cannot find module './.yo-rc.json'
  at Function.Module._resolveFilename (module.js:338:15)
  at Function.Module._load (module.js:280:25)
  at Module.require (module.js:364:17)
```
tried upgraded yeoman to no avail: wondering if we need a .yo-rc.json for auto installation of webdriver to succeed?

**Comment by eduardosanzb** [comment]
@awashbrook did u manage to solve the`Cannot find module './.yo-rc.json'` problem?
